name: Deploy to Surge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build and Deploy
      run: | 
        npm install --global surge
        surge 
        surge --project ./ --domain http://devopsgamespage.surge.sh --token 9c77f45911e6a68b5abbc0f3b70bf620  
